# Configuration of the CI pipeline
name: 'Lemp'
canonical: 'stack-lemp'
description: 'Used to deploy a php application on X Amazon EC2 instances behind an ALB load balancer (Linux, Nginx, MySQL, PHP ...).'
keywords:
  - 'lemp'
  - 'linux'
  - 'nginx'
  - 'mysql'
  - 'php'
technologies:
  - technology: Debian
    version: 9.x
  - technology: Nginx
    version: 1.1x
  - technology: php-fpm
    version: 7.2
  - technology: mysql
    version: 5.7.x
  - technology: redis
    version: 5.x
  - technology: s3
    version: n/a

author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/stack-lemp/master/icon.png'
type: 'stack'
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/lemp.yml'
    variables:
      path: 'pipeline/variables.sample.yml'

  # Configuration of ansible for provisionning
  ansible:
    front:
      path: 'ansible/environments/front.yml.sample'
      destination: '($ project $)/ansible/environments/($ environment $)-front.yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    lemp:
      path: 'terraform/lemp.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/lemp.tf'
